const steps = [
    {
        name: 'Kuala Lumpur & Malacca',
        country: 'Malaisie',
        lat: 3.139,
        lng: 101.6869,
        number: 1,
        duration: '4 jours',
        budget: '75 €',
        note: 'Petronas, Batu Caves et les ruelles de Malacca',
        story: [
            'Départ en bus direct depuis Singapour pour environ cinq heures de trajet à travers les immenses plantations de palmiers à huile de la péninsule malaise. Arrivée à Kuala Lumpur, marquée par le contraste entre les gratte-ciels du quartier d\u2019affaires et les maisons traditionnelles plus modestes. Visite des tours Petronas illuminées en soirée, de la KL Tower et de Chinatown avec ses étals de street food où l\u2019on goûte notamment au nasi goreng.',
            'Excursion au nord de la ville aux Batu Caves pour gravir les 272 marches colorées menant aux sanctuaires creusés dans la roche calcaire. La suite de l\u2019étape se poursuit en bus vers le sud à Malacca, ville portuaire historique classée à l\u2019UNESCO : découverte des façades rouges néerlandaises de Christ Church, des ruines portugaises de la forteresse A Famosa et de l\u2019animation de Jonker Street.',
        ],
    },
    {
        name: 'Sud de la Thaïlande',
        country: 'Thaïlande',
        lat: 8.0863,
        lng: 98.9063,
        number: 2,
        duration: '7 jours',
        budget: '390 €',
        note: 'Krabi, Phuket, Phi Phi, Khao Sok et Phang Nga',
        story: [
            'Traversée terrestre en bus vers la côte d\u2019Andaman au sud de la Thaïlande. Étape d\u2019abord posée entre Krabi et la péninsule de Railay, réputée pour ses falaises karstiques plongeant dans la mer, avant de rejoindre l\u2019île de Phuket. Embarquement ensuite en ferry pour l\u2019archipel de Koh Phi Phi, avec ses criques encadrées de parois rocheuses et ses fonds marins.',
            'Changement de décor vers l\u2019intérieur des terres avec l\u2019exploration du parc national de Khao Sok : randonnée dans la jungle tropicale et navigation en pirogue à moteur sur le lac Cheow Lan au milieu des pitons calcaires. Le circuit se complète par une excursion en bateau dans la baie de Phang Nga, entre îlots rocheux spectaculaires et le village de pêcheurs sur pilotis de Koh Panyee.',
        ],
    },
    {
        name: 'Bali & Java',
        country: 'Indonésie',
        lat: -8.5069,
        lng: 115.2625,
        number: 3,
        duration: '13 jours',
        budget: '700 €',
        note: 'Rizières de Jatiluwih, Ijen, Bromo et Borobudur',
        story: [
            'Vol depuis Singapour vers l\u2019île de Bali. Début du séjour sur la côte à Seminyak, puis immersion à Ubud au cœur de l\u2019île pour explorer les rizières en terrasses de Jatiluwih, irriguées selon le système traditionnel Subak et classées au patrimoine mondial de l\u2019UNESCO.',
            'Traversée en ferry vers l\u2019île de Java pour entamer un itinéraire ferroviaire d\u2019est en ouest. Ascension nocturne du volcan Kawah Ijen pour observer son cratère d\u2019acide sulfurique et le travail des mineurs de soufre, suivie du lever de soleil sur la caldeira fumante du mont Bromo. Le voyage continue en train vers Yogyakarta pour visiter le grand temple bouddhique de Borobudur et les sanctuaires de Prambanan, avant de rejoindre la capitale Jakarta pour le vol retour.',
        ],
    },
    {
        name: 'Bornéo',
        country: 'Malaisie',
        lat: 5.839,
        lng: 118.1164,
        number: 4,
        duration: '5 jours',
        budget: '330 €',
        note: 'Orangs-outans de Sandakan et rivière Kinabatangan',
        story: [
            'Vol intérieur de Kuala Lumpur vers Sandakan, située dans l\u2019État du Sabah à l\u2019extrémité nord-est de Bornéo. Visite du centre de réhabilitation des orangs-outans de Sepilok, créé pour soigner et réacclimater à la vie sauvage les primates orphelins ou rescapés de la déforestation.',
            'Immersion de deux jours le long du fleuve Kinabatangan, l\u2019un des écosystèmes les plus riches d\u2019Asie du Sud-Est. Safaris en petite barque à moteur à l\u2019aube et en fin d\u2019après-midi pour observer les singes nasiques, calaos, crocodiles d\u2019estuaire et éléphants pygmées, avec des nuits passées en écolodge sur les rives du fleuve.',
        ],
    },
    {
        name: 'Shanghai',
        country: 'Chine',
        lat: 31.2304,
        lng: 121.4737,
        number: 5,
        duration: '5 jours',
        budget: '175 €',
        note: 'Le Bund, Pudong et les jardins de Yuyuan',
        story: [
            'Arrivée à Shanghai par avion depuis Bornéo. Déplacements quotidiens à vélo partagé et en métro pour parcourir la métropole. Balade incontournable sur la promenade du Bund, offrant un panorama direct sur la skyline ultramoderne de Pudong (Shanghai Tower, Jin Mao et Oriental Pearl) de l\u2019autre côté du fleuve Huangpu.',
            'Parcours des avenues ombragées de l\u2019ancienne concession française avec ses bâtisses des années 1920 et ses ruelles résidentielles. Découverte du jardin Yuyuan au cœur du vieux Shanghai, avec ses pavillons d\u2019époque Ming et ses étangs de carpes, avant de prendre le train à grande vitesse (TGV) reliant Shanghai à Pékin en un peu plus de quatre heures.',
        ],
    },
    {
        name: 'Pékin',
        country: 'Chine',
        lat: 39.9042,
        lng: 116.4074,
        number: 6,
        duration: '5 jours',
        budget: '290 €',
        note: 'Cité interdite, Temple du ciel et Grande Muraille',
        story: [
            'Arrivée en TGV au cœur de la capitale chinoise. Visite de la place Tiananmen et de l\u2019immense complexe de la Cité interdite, complétée par la montée au parc Jingshan pour une vue plongeante sur l\u2019ensemble des toitures impériales. Découverte du Temple du Ciel (Tiantan), du Palais d\u2019été et du temple tibétain des Lamas (Yonghegong).',
            'Excursion d\u2019une journée vers la Grande Muraille de Chine sur la portion de Mutianyu, située à environ 70 km au nord-est de la ville. Randonnée le long des remparts crénelés et des tours de garde qui épousent les crêtes montagneuses, dans un secteur boisé et nettement moins fréquenté que celui de Badaling.',
        ],
    },
    {
        name: 'Séoul',
        country: 'Corée du Sud',
        lat: 37.5665,
        lng: 126.978,
        number: 7,
        duration: '7 jours',
        budget: '245 €',
        note: 'Gyeongbokgung, Gangnam, Hongdae et Itaewon',
        story: [
            'Vol court reliant Pékin à Séoul. Découverte du patrimoine historique avec le palais royal de Gyeongbokgung et sa cérémonie de relève de la garde, puis balade dans les ruelles préservées du village traditionnel de Bukchon Hanok, entre maisons anciennes en bois et vue sur les gratte-ciels en arrière-plan.',
            'Exploration des différents quartiers de la capitale : l\u2019animation étudiante et créative de Hongdae, le quartier international d\u2019Itaewon adossé au mont Namsan, et les grandes artères commerçantes de Gangnam. Le séjour est rythmé par la street food des marchés locaux (tteokbokki, kimbap) et les repas autour des traditionnels barbecues coréens.',
        ],
    },
    {
        name: 'Taïwan',
        country: 'Taïwan',
        lat: 25.033,
        lng: 121.5654,
        number: 8,
        duration: '6 jours',
        budget: '250 €',
        note: 'Taipei, Alishan et le Bitoujiao Trail',
        story: [
            'Vol de Séoul vers Taipei, puis déplacements sur l\u2019île grâce au réseau ferroviaire taïwanais. Découverte de la capitale, dominée par la tour Taipei 101, et des marchés de nuit réputés comme Raohe et Shilin pour goûter aux spécialités locales et aux thés aux perles. Excursion côtière sur le sentier panoramique de Bitoujiao, qui longe les crêtes rocheuses face à l\u2019océan Pacifique.',
            'Trajet en train puis en bus vers le parc national d\u2019Alishan au centre de l\u2019île. Randonnée matinale au milieu des cyprès géants millénaires et découverte de la ligne de chemin de fer forestière historique serpentant à flanc de montagne dans une atmosphère brumeuse caractéristique.',
        ],
    },
    {
        name: 'Hong Kong',
        country: 'Chine',
        lat: 22.3193,
        lng: 114.1694,
        number: 9,
        duration: '5 jours',
        budget: '260 €',
        note: 'Dragon\u2019s Back, Tsim Sha Tsui et Bouddha de Tian Tan',
        story: [
            'Vol depuis Taipei vers Hong Kong. Immersion immédiate dans la densité urbaine entre la promenade de Tsim Sha Tsui face à Victoria Harbour, la traversée historique en Star Ferry vers l\u2019île de Hong Kong et les ruelles animées des marchés de Mong Kok.',
            'Randonnée sur le sentier du Dragon\u2019s Back, situé au sud-est de l\u2019île, offrant des vues dégagées sur les collines verdoyantes, les criques et la mer de Chine méridionale. Excursion en ferry vers l\u2019île de Lantau pour gravir les marches menant au grand Bouddha de bronze de Tian Tan et visiter le monastère bouddhiste de Po Lin.',
        ],
    },
    {
        name: 'Vietnam',
        country: 'Vietnam',
        lat: 21.0278,
        lng: 105.8342,
        number: 10,
        duration: '12 jours',
        budget: '460 €',
        note: 'Hanoi, Ninh Binh, Bai Tu Long et Ho Chi Minh',
        story: [
            'Vol depuis Hong Kong vers Hanoï, point de départ d\u2019une traversée du pays du nord au sud combinant bus locaux et trains de nuit. Découverte du quartier des 36 corporations à Hanoï et de ses cafés traditionnels, suivie d\u2019une croisière de deux jours dans la baie de Bai Tu Long, secteur plus calme et préservé situé à l\u2019est de la baie d\u2019Ha Long.',
            'Étape dans la région de Ninh Binh pour naviguer en barque à rames au cœur des paysages karstiques et des rizières de Tam Coc et de la réserve de Vân Long. Descente en train vers le sud jusqu\u2019à Hô Chi Minh-Ville (Saigon), avec ses marchés couverts, ses édifices historiques coloniaux et ses étals de pho à tous les coins de rue.',
        ],
    },
    {
        name: 'Chiang Mai & Bangkok',
        country: 'Thaïlande',
        lat: 18.7883,
        lng: 98.9853,
        number: 11,
        duration: '9 jours',
        budget: '270 €',
        note: 'Chiang Rai, temples et street food',
        story: [
            'Vol direct de Hanoï vers Chiang Mai, au nord de la Thaïlande. Découverte de la vieille ville fortifiée, montée au temple perché de Wat Phra That Doi Suthep dominant la vallée, et excursion en bus vers Chiang Rai pour visiter le temple blanc contemporain de Wat Rong Khun et les collines avoisinantes.',
            'Liaison en bus vers Bangkok pour clôturer l\u2019étape thaïlandaise : visite du Grand Palais et du Wat Pho avec son immense Bouddha couché, navigation en bateau-bus sur le fleuve Chao Phraya pour explorer les canaux (klongs) de Thonburi, et découverte des marchés nocturnes réputés pour leur street food.',
        ],
    },
    {
        name: 'Cambodge',
        country: 'Cambodge',
        lat: 13.3671,
        lng: 103.8444,
        number: 12,
        duration: '4 jours',
        budget: '265 €',
        note: 'Angkor, Siem Reap et Phnom Penh',
        story: [
            'Vol de Bangkok à Siem Reap pour explorer le parc archéologique d\u2019Angkor en tuk-tuk sur deux journées complètes. Lever de soleil sur les tours d\u2019Angkor Wat, découverte des 216 visages de pierre sculptés du temple du Bayon à Angkor Thom, et passage par Ta Prohm, laissé en partie envahi par les racines géantes d\u2019arbres fromagers.',
            'Trajet en bus à travers les campagnes cambodgiennes jusqu\u2019à la capitale Phnom Penh, située à la confluence du Mékong et du Tonlé Sap : visite du Palais royal, de la Pagode d\u2019argent et des marchés de la ville, avec un aperçu de l\u2019histoire contemporaine du pays.',
        ],
    },
    {
        name: 'Dubaï',
        country: 'Émirats Arabes Unis',
        lat: 25.2048,
        lng: 55.2708,
        number: 13,
        duration: '7 jours',
        budget: '440 €',
        note: 'Old City, Palm Jumeirah et Burj Khalifa',
        story: [
            'Dernière grande escale du voyage avec un vol Emirates au départ de Singapour vers Dubaï. Visite des quartiers historiques de Deira et Bur Dubai le long du Creek, traversée en bateau-taxi traditionnel (abra) entre les souks aux épices et de l\u2019or, contrastant avec l\u2019urbanisme spectaculaire du reste de l\u2019émirat.',
            'Découverte des infrastructures emblématiques : montée aux plateformes panoramiques du Burj Khalifa dominant le Dubai Mall et ses bassins de fontaines, promenade le long des quais de la Dubai Marina bordée de gratte-ciels résidentiels, et passage sur l\u2019archipel artificiel de Palm Jumeirah avant de préparer le vol retour définitif.',
        ],
    },
];
